steps:
- name: 'docker'
  args: ['build', '-t', '$$IMAGE', '.']
  secretEnv: ['IMAGE']
availableSecrets:
  secretManager:
  - versionName: projects/sysadmin-151815/secrets/emren-test1/versions/1
    env: IMAGE
