steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$image', '.']
  secretEnv: ['image']
availableSecrets:
  secretManager:
  - versionName: projects/sysadmin-151815/secrets/emren-test1/versions/2
    env: image
