steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-e','MYSQL_ROOT_PASSWORD=$$my-secret-pw', '-t', 'gcr.io/sysadmin-151815/emren-test:v2', '.']
  secretEnv: ['my-secret-pw']
availableSecrets:
  secretManager:
  - versionName: projects/sysadmin-151815/secrets/emren-test1/versions/3
    env: my-secret-pw
