apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "my-app"
  namespace: "default"
  labels:
    app: "my-app"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "my-app"
  template:
    metadata:
      labels:
        app: "my-app"
    spec:
      containers:
      - name: "my-app"
        image: "image_here"
        ports:
          - containerPort: 3000
            name: "my-app"

---
apiVersion: "apps/v1"
kind: "Service"
metadata:
name: "my-app"
labels:
  app: "my-app"
spec:
ports:
  - port: 80
    targetPort: 3000
selector:
  app: "my-app"
  tier: "my-app"
type: LoadBalancer