apiVersion: "v1"
kind: "Secret"
metadata:
  name: "my-app-secret"
  namespace: "default"
type: kubernetes.io/tls
data:
  tls.crt: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNzekNDQVpzQ0ZFZFVtaTVkWit6MzlKeUduSmdLS0tIRlA0UjZNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1CWXgKRkRBU0JnTlZCQU1NQ3lvdVpXMXlaVzR1WTI5dE1CNFhEVEl4TURJeU5qQTNNalUwT1ZvWERUTXhNREl5TkRBMwpNalUwT1Zvd0ZqRVVNQklHQTFVRUF3d0xLaTVsYlhKbGJpNWpiMjB3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBCkE0SUJEd0F3Z2dFS0FvSUJBUURiTTRmbEJxTVBjd2JUUURMQXUzS1pQa1ZxZGZkZVBoLzM3dkZqS0xkNUhOdkYKSjUzQTJYLzdGR2VIQkUvK1g1SGNCeVlrVitLb3cveEJtbVdEcjdtQ0NLZXV1dEhQZG5VejBRNVcwWkxpMVl1awp3NEF0M3BJYjRrRTJLUVozcjVGVGZHZXc3SGJHa1prR21LRTVnem5LYm9aZURvbEFRZjN1U1JoWE5SQjFYYys2CnE2MDFLdEhibTMxZzdBbUd0aDdZM3BLTkFjbFlsaXFiM2Nsb1B4c0VKTnovMFoxakhUUDNtYVZXTy8wR3ZxQ0QKbGh0TEhtbDVsWXFBZXNxYzF4N2ZuTUFEVUUrUVdHT1RFNytkTzJiWlRjM1JsZlVxTUhSNURLK2dFU1NQNUxRRgp0b3hFdmRPQlVGYW1iYXFQYVpQSDZSanZwWUtYTGFxQ2QrQ3h1UzVCQWdNQkFBRXdEUVlKS29aSWh2Y05BUUVMCkJRQURnZ0VCQUpDWjdxTEFjdzY1NmJNblVqejlaUDU2S1Q3UkI0T0pWR1FwQ3FvZFgwcThmSWFiYnlRbjd3MzcKbTczWDVSQlZUTEdvWHgxMmIxUzBvMXlXbWJuUGtTT01wTGpDVHB4TUc5SGlLZTAwcFRSeTFrSGNGWithRm9xLwphYm1yUnh4cU53NGVvM3hjSG4wMFR5b3FxZDlsZGJQLzl2WlpHbnc2bS9UQ0NuMlRQczNGZ3d2Y243Qyt1RHJmCk1wYkQ3cXRqVi9GRWZUUHBoQ1BKbExpanpuNjUwNjFWSC92Q1IzWkUraTR5THlkZ1R6VTA5bVFOS0p0MUx3QWYKUUQ1aURYRkhqRDNsby81SHo0SExWaWNQUzB3Vkc0aGxRZ2wwQ05XTGhpU2lZYTZlVnp2MGhUaThLeGh6dWV3WApLMjFuc1dVUy8zdC9mVGVVL0NjZHYzRmY2Q2VZUDRZPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
  tls.key: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBMnpPSDVRYWpEM01HMDBBeXdMdHltVDVGYW5YM1hqNGY5Kzd4WXlpM2VSemJ4U2VkCndObC8reFJuaHdSUC9sK1IzQWNtSkZmaXFNUDhRWnBsZzYrNWdnaW5ycnJSejNaMU05RU9WdEdTNHRXTHBNT0EKTGQ2U0crSkJOaWtHZDYrUlUzeG5zT3gyeHBHWkJwaWhPWU01eW02R1hnNkpRRUg5N2trWVZ6VVFkVjNQdXF1dApOU3JSMjV0OVlPd0poclllMk42U2pRSEpXSllxbTkzSmFEOGJCQ1RjLzlHZFl4MHo5NW1sVmp2OUJyNmdnNVliClN4NXBlWldLZ0hyS25OY2UzNXpBQTFCUGtGaGpreE8vblR0bTJVM04wWlgxS2pCMGVReXZvQkVraitTMEJiYU0KUkwzVGdWQldwbTJxajJtVHgra1k3NldDbHkycWduZmdzYmt1UVFJREFRQUJBb0lCQVFDSjkvdFhHa0JVSHhCeQpzdnUrOTd6LzI0UVJxRUtVM1FGK0tyVmd0bVlWSXlicEJ6QnlDL1JUOHRuZXo4WVIwOUdZN2g4QnpSZHJKa0NHCmdrblhBeW4rUUxoYWNGaFMvcnB5Yk9sYmwvbWVNTTcrVzljNEI5bHJGNVA0SlFaZkd2Q2IzYmZlVWxmSVVDaEQKVUpwWit0RExLNW9EWlo3YUJTOXhaaXlkNTFaK3ArMHc2amt2aHNZZDlISGF6SGZZbmFoRmc5L3JveUV5ekwyWApxamJlSS9XRy93ZTR0UkdldFdDNnJUTDVmQXN4cE1BeEJJQkFpTnRzL1NMY0F2Qkk5RGJsZGpxVmxzWFcxZ0l4CmJ6dm5NNzhvT3dFelF1STZQNVl0cnFxNkNIa3lmc2MyMDgzaWJLOWNpaUNzTDF1WmtJWit4VnZlUUFTOVpZZWcKUllpMVRkb0pBb0dCQVBFNDc5OS9MRGhCaGU0bVk2Tk9ucTVWYzBnd21KS1RqUHBXdzVJSUhKMVRuRjZDK2dENwowVHJhSExlSDFNUk9iOHlBVDFCTUVrYlNaZDNmRFhlcXZCa2piM2ZVNVNJWnZMZ2lmTFhKdE5oaHdwR1l6eGRLCldheDVBUGE4QzBuSm43amhIT1hLbzlKUnJTcHVVNXc0YmhuZEZXNWZTL3FqZXZQajBCUWMxTnJYQW9HQkFPaWgKUFR5TmZuak45cUV4bE9nZUhiYnJoL1FjdDhjSlJBVUMzRENMOGNOWEtaWW93Zk1rQ3EwcVFyR0VMMUFyRzZSQQpuT21zTUlwVkhTR3Vvb0lUUVZic3ZSQk5sdWkzQ2xSc0FFVy8wVHp1a0EzL1ZUL1M1UERhWHFoUThiYm83SnZJCmVKclZQWUV2UjlZNTNUYVB6ZUxhampFUVpOVVZvWlFLY3BIa1UzU25Bb0dBVDRwQXZtZUd3ejRIMVpGZkJYaGwKSm9NU3Nsa2oxaUZGT1Q3bTJmNUd3VEhTdSs5Z1ZIYTBkVDE2ZnFJUmJIR1l0OHdQV3lEYVhmUCtsdngzeWwvSQpDbG4rNVhxVDIzeTFGOXAzV05JY0NjV2lqTFBnaFlPRXNqUnNOdSttb1R3VXFMZkIrWnVxRFMzVmRjcFBVNUhmCjdETlVYOEtZb1JySzdpVE9kZk5UMUowQ2dZQTE3T3FkRnMreWdVd2lvYk82K3dBNFh2RHREWnNzY0dGc0ovV1MKNjEzbndsVEpramtqZTc5ZDFPWVE4R3RuVWhiZVJId2JUdWNScWhsT3JZVE9VbGhiSmhYTnFhN0owMlI1blcrUwp1NXh0VzMvWlBzOHNORjhOMWhFTFEzaEV4a25TOHUzQ05weERUZ3FCQm5qWkpReTlBWnpra3NCTkJPNm51cVJFClhZRmJFUUtCZ0V3bVBXWnRCOVNiUXE5UkR1NzE1V2VmdmsrWkZad3ZpeXprYmY4R3R1d2VEczlxWG52bjFrZEMKSktSMkdSOStFTlBwczBZbXd5Z2h1U3dhR3lETXFkeG50OUJWQ1RuUVhMK1QxL3lOQWJ1N2NZbVQ1NnVoY0l0SAp4eVl1alRvVU44UkEwSUEzLy9iMDdBcHpVWk82b0gzMi91cFhsS2ZNUzk2RHBCZFQyRnVOCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg=="

---

apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "my-app"
  namespace: "default"
  labels:
    app: "my-app"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "my-app"
  template:
    metadata:
      labels:
        app: "my-app"
    spec:
    volumes:
      - name: secret-volume
        secret:
          secretName: my-app-secret
      containers:
      - name: "my-app"
        image: "namli/my-node-app-image:v11"
        ports:
          - containerPort: 3000
            name: "my-app"
     volumeMounts:
      - mountPath: /var/www/ssl
        name: secret-volume

---

apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 443
      name: https
      targetPort: 3000
  type: LoadBalancer
