apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "my-app"
  namespace: "default"
  labels:
    app: "my-app"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "my-app"
  template:
    metadata:
      labels:
        app: "my-app"
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: my-app-secret
      containers:
        - name: "my-app"
          image: "namli/my-node-app-image:v11"
          ports:
            - containerPort: 3000
              name: "my-app"
          volumeMounts:
            - mountPath: /var/tmp
              name: secret-volume

---

apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 443
      name: https
      targetPort: 3000
  type: LoadBalancer
